### ISSUE TITLE
[Calendar] Remove Unnecessary Features from Calendar Page

### ISSUE THREAD

**Issue by UKCSD** [cse110-sp24-group30/cse110-sp24-group30#111]
### Objectives
Remove unnecessary features that bloat up the calendar page and don't really benefit the user experience overall. The objective is to clean up the ui and make the calendar feel more intuitive to use.

### Acceptance Criteria
- [x] Remove the category sorter from the calendar header
- [x] Remove the options to pick the recurrence as well as the reminder when editing/creating a new task

### Assignees
- @UKCSD

**Comment by AliMohammadiasl** [comment]
All done and looks good!
