### ISSUE TITLE
[To-Do] [Calendar] Sync To-Do List with Calendar

### ISSUE THREAD

**Issue by kabirsachdev7** [cse110-sp24-group30/cse110-sp24-group30#81]
### Objectives
The goal of this issue is to be able to sync all the tasks being added to the to-do list to automatically be reflected onto the calendar module as well. This will allow our product to have encompass seamless integrations across all modules and link the code with each other. 

### Acceptance Criteria
- [x] `to-do` and `calendar` files are linked with each other
- [x] Changes made to a task on the to-do list and have a date set is displayed on the calendar widget too

### Assignees
- @kabirsachdev7 
- @shjucsd 
- @ChooChooChao

**Comment by shjucsd** [comment]
I made changes under the todo branch such that the calendar is updated as the tasks are created/modified/deleted.
